### ISSUE TITLE
More docmentation

### ISSUE THREAD

**Issue by Knot-Here** [pyth-network/pyth-client-py#35]
Hi, just wondering how I would:

- get a list of oracles available on pyth?
- query price date at historical points/ranges?

thank you

**Comment by jayantk** [comment]
Hi @Knot-Here . For your second question, check out the benchmarks api https://docs.pyth.network/benchmarks . 

and can you say more about your first question? What do you mean by "oracles"?

**Comment by jayantk** [comment]
Oh if you're asking for what assets we have prices for, check out https://pyth.network/price-feeds

**Comment by jayantk** [comment]
i think we answered these question, so closing. please feel free to reopen if you think we did not (or just reach out in discord)

**Comment by Knot-Here** [comment]
i meant how to call this list of assets within python and also query a historical range of data, but i missed this, sorry!
